### PR TITLE
ros2 wrapper

### PR DESCRIPTION
**Pull request by ejharber**

### CODE REVIEW

**Comment by Lucky7Chess** [comment]
I'm going to test this locally and make a separate folder for ros2 support ASAP.   Thank you for the help!

**Comment by soham2560** [comment]
any updates on this?

**Comment by likecanyon** [comment]
Can we use this ros2module to deploy the simulation?

**Comment by Lucky7Chess** [comment]
I made a different ros2 module that sort of parallels the ros1 one, this could be useful for some people though.

**Pull request closed without merging**
